config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'hobbies', to: 'pages#hobbies'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50}
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
  validates :user_id, presence: true 
end 

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end
 

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all.paginate(page: params[:page], per_page: 5)
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else 
      render 'new'
    end
  end

  

  def show
    
  end

  def new
    @article = Article.new
  end

  def edit
    
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else 
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end


  private

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = "you can only edit or delete your own articles"
      redirect_to root_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5 )
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end

  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
        flash[:success] = "Category name was succesfully updated"
        redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to  user_path(user)
    else 
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:edit, :update, :show]
  before_action :require_same_user, only:[:edit, :update, :destroy]
  before_action :require_admin, only:[:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end


  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "you can only edit your own account"
      redirect_to root_path
    end
  end

  def require_admin
    if looged_in? and !current_user.admin? 
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
  end  
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="card-body">
    <%= link_to article.title, article_path(article), class: "card-title article-title" %><hr>
    <%= truncate(article.description, length: 100, class: "card-text") %> <br>
    <div class="article-meta-data">
    <small>Created by: <%= article.user.username %>,
                       <%= time_ago_in_words(article.created_at) %> ago,
         last updated: <%= time_ago_in_words(article.updated_at) %> ago
    </small>
    </div>
  </div>
  <% if article.categories.any? %>
    <p><%= render article.categories %></p>
  <% end %>
  <% if logged_in? && (current_user == article.user || current_user.admin?) %>
    <div class="card-footer text-muted">
      <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %> 
      <%= link_to "Delete this article", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-xs btn-danger" %> 
    </div>
  <% end%>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="form-group row">
  <div class="col-sm-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %><br>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %><br>
        </div> 
        <div class="col-sm-10"> 
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article", autofocus: true %>
        </div>
      </div>
      <div class="form-check form-check-inline">
        <div class="col-sm-12">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
            <% cb.label(class: "form-check-label") {cb.check_box(class: "form-check-input") + cb.text} %>
          <% end %>
        </div>
      </div><br>
      <div class="form-group">
        <div class="col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>

    <% end %>
    <div class="col-sm-4 col-sm-offset-4">
      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="text-center"><%= will_paginate(@things, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %></div>
<div class="card text-center">
  <div class="card-header">
    <h1 align="center">Listing all articles</h1>
  </div>
  <%= render 'article', obj: @articles %>
</div>
<div class="text-center"><%= will_paginate(@things, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %></div>

app/views/articles/new.html.erb
<h1 align="center">Create a New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="card text-center">
  
  <div class="card-header">
    Title: <%= @article.title %>
  </div>
  <% if @article.user %>
  <div class="card-body">
    <p class="card-text">Created by:</p>
    <p class="card-text"><%= link_to gravatar_for(@article.user), user_path(@article.user) %></p>
    <h4 class="card-title"><strong>Description</strong></h4>
    <p class="card-text"><%= link_to @article.user.username, user_path(@article.user) %></p>
    <p class="card-text"><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></p>
    <hr>
  </div>
  <% end %>
  <div class="card-body">
    <h4 class="card-title"><strong>Description</strong></h4>
    <hr>
    <p class="card-text"><%= simple_format(@article.description) %></p>
  </div>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <div class="card-footer text-muted">
  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
    <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
    <%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-xs btn-danger" %> 
  <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-secondary"><%= link_to category.name, category_path(category)%>&nbsp;</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :name %><br>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>

<% end %>
<div class="col-sm-4 col-sm-offset-4">
  [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="card text-center">
  <div class="card-header">
    <h1 align="center">Listing all categories</h1>
  </div>
  <div class="text-center"><%= will_paginate(@things, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %></div>
  <% @categories.each do |category| %>
  <h4 class="card-title"><%= link_to "#{category.name}", category_path(category) %></h4>
  <p><small><%= pluralize(category.articles.count, "article") %></small></p>
  <% end %>
</div>
<div class="text-center"><%= will_paginate(@things, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %></div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="text-center"><%= will_paginate(@category_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %></div>
<div class="card text-center">
  <div class="card-header">
    <h1 align="center"><%= "Category:" + @category.name %></h1>  
  </div>
  <% if logged_in? and current_user.admin? %>
  <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
  <% end %>
  <%= render 'articles/article', obj: @category_articles %>
</div>
<div class="text-center"><%= will_paginate(@category_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %></div>  

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  Copyright © <a href="enter in a link here">The Complete Ruby on Rails Developer</a>
  by <a href="enter in a link here">Mashrur Hossain</a>
  </small>

  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm-10">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All Categories", categories_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <% Category.all.each do |category| %>
            <a class="dropdown-item"><%= link_to "#{category.name}", category_path(category) %></a>
          <% end %>
          <% if logged_in? and current_user.admin? %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item"><%= link_to "Create New Category", new_category_path %></a>
          <% end %>
        </div>
        </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <% if logged_in? %>
          <%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact Me", contact_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Your Profile<%= " Admin" if current_user.admin? %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
          <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
      <%= link_to "Log in", login_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to "Sign up", signup_path, class: "nav-link" %>
      <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class='container'>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>
<%= link_to 'Home', root_path %>

app/views/pages/contact.html.erb
  <h1>Mike's Contact Information</h1>

  <h3>119 Maple Road Bonfield On Canada</h3>
  <h3>705-776-7332</h3>
  <h3>Cell 705-499-6252</h3>
  <h3>email mike.andrews357@gmail.com</h3>
  <h3>facebook Michael John Andrews</h3>
  <hr>
  <form action="mailto:mike.andrews357@gmail.com" method="post" enctype="text/plain">
    <label for="">Your Name:</label>
<input type="text" name="yourName" value=""><br>
    <label for="">Your Email:</label>
<input type="email" name="yourEmail" value=""><br>
    <label for="">Your Message:</label><br>
    <textarea name="yourMessage" id="" cols="30" rows="10"></textarea><br>
    <input type="submit" name="">
  </form>

app/views/pages/hobbies.html.erb
  <h1>Mikes Hobbies</h1>
  <ul>
    <li>Competitive Shooting</li>
    <li>Motorcycling</li>
    <li>Working with Tractor</li>
    <li>Web Design</li>
    <li>Building Shooting Ranges</li>
    <li>Micro controllers</li>
    <li>Reloading ammo for Shooting</li>
  </ul>
  <ol>
    <li>Pistol Shooting</li>
    <li>Rifle Shooting</li>
    <li>Shotgun Sports</li>
    <li>Arduino Tech</li>
    <li>Learning about Web Development</li>
    <li>Working with Heavy Equipment</li>
  </ol>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1 class="display-4">Alpha Blog</h1> 
  <h2>Michael Andrews</h2><br><br><br>
  <p><em>Aspiring</em> Web Developer</p>
  <p>I am a retired old fart learning new technology and having fun on the journey. My interests also are in Competitive Firearms <a href="https://www.ipsc-ont.org/" target="_blank">shooting</a> and Volunteeer Work at the Gun Club where I belong.</p>     
  <%= link_to "Sign up Now", signup_path, class: "btn btn-danger btn-lg btn-xlarge"%>
</div>



  <hr>
  <h3>Education</h3>
  <ul>
    <li>Management Supervisor Program</li>
    <li>Power Maintenance Electrician Apprenticeship</li>
    <li>Northern College of Technology and Mines - Electrical Engineering Technician</li>
    <li>Iroquois Falls Secondary High School</li>
  </ul>
<hr>
  <h3>Work Experience</h3>
  <table>
    <thead>
    <tr>
      <th>Dates</th>
      <th>Work</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>2013 - Present</td>
      <td>Retired and Working for Fun</td>
    </tr>
    <tr>
      <td>1999 - 2013</td>
      <td>Trades Management Supervisor, Ontario Power Generation Inc</td>
    </tr>
    <tr>
      <td>1981 - 1999</td>
      <td>Power Maintenance Electician, Ontario Hydro</td>
    </tr>
    </tbody>
    <tfoot>
    </tfoot>
  </table>
  <hr>
  <h3>Skills</h3>
  <table cellspacing="35">
    <tr>
      <td>
        <table>
          <tr>
            <td>HTML5</td>
            <td>★★★☆☆</td>
          </tr>
          <tr>
            <td>Bootstrap Framework</td>
            <td>★★☆☆☆</td>
          </tr>
          <tr>
            <td>CSS(3)</td>
            <td>★★★☆☆</td>
          </tr>
          <tr>
            <td>Javascript</td>
            <td>★★☆☆☆</td>
          </tr>
          <tr>
            <td>Ruby</td>
            <td>★★☆☆☆</td>
          </tr>
        </table>
      </td>
      <td>
        <table>
          <tr>
            <td>Welding</td>
            <td>★★★☆☆</td>
          </tr>
          <tr>
            <td>Electrician</td>
            <td>★★★★☆</td>
          </tr>
          <tr>
            <td>Operating Heavy Equipment</td>
            <td>★★★★☆</td>
          </tr>
          <tr>
            <td>Surveying</td>
            <td>★★★☆☆</td>
          </tr>
          <tr>
            <td> Climbing Arborist</td>
            <td>★★★☆☆</td>
          </tr>
        </table>
      </td>
  </table>
  <hr>
  <h3><a href="hobbies.html"></h>My Hobbies</a></h3>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="alert alert-danger" role="alert">
          <h2 class="alert-heading">
          <%= pluralize(obj.errors.count, "error") %> prohibited this article from being saved: 
          </h2>
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="form-group row">
  <div class="col-sm-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %><br>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %><br>
        </div> 
        <div class="col-sm-10"> 
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %><br>
        </div> 
        <div class="col-sm-10"> 
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-10">
          <%= f.submit(@user.new_record? ? "Signup" : "Update account", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>

    <% end %>
    <div class="col-sm-4 col-sm-offset-4">
      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account info</h1>

<%= render 'shared/errors', obj: @user %>
<%= render 'form' %> 

app/views/users/index.html.erb
<div class="text-center"><%= will_paginate(@things, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %></div>
<div class="card text-center">
  <div class="card-header">
    <h1 align="center">All Alpha Bloggers</h1>
  </div>
  
  <%= @users.each do |user| %>
  <div class="card-body">
    <p class="card-text"><%= link_to gravatar_for(user), user_path(user) %></p>
    <h4 class="card-title"><strong>Description</strong></h4>
    <p class="card-text"><%= link_to user.username, user_path(user) %></p>
    <p class="card-text"><small><%= pluralize(user.articles.count, "article") if user.articles %></small></p>
    <% if logged_in? and current_user.admin? %>
      <p class="card-text"><%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete the user and all their articles?" } %></p>
    <% end %>
    <hr>
  </div>
  <% end %>
  
</div>
<div class="text-center"><%= will_paginate(@things, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %></div>

app/views/users/new.html.erb
<h1 align="center">Signup for Alpha Blog</h1>

<%= render 'form' %> 

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class="row">
    <div class="col-md-12 center">
    <%= gravatar_for @user, size: 150 %>
    </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<div class="center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="center">
  <%= will_paginate @user_articles %>
</div>